### ISSUE TITLE
What website to build?

### ISSUE THREAD

**Issue by alexislyndon** [m0L3cuL3/ITCC-13-FINAL-PROJECT#1]
Whose website to build? 
Who will see/use the site?
How often will we work on it? 

**comment any and all ideas here!**

**Comment by m0L3cuL3** [comment]
We wait for Ceon

**Comment by alexislyndon** [comment]
@C30N @m0L3cuL3 @MichaelPagaran @EdwardRosales12 
So unsa iyang website need ni SMB italian foods client?

**Comment by C30N** [comment]
Naa ta reference link. Yellow cab delivery site

Kato ra ato basihan

Contents kay

* Order method
* menu list
* info dayon sa company

**Comment by alexislyndon** [comment]
https://delivery.yellowcabpizza.com
