### ISSUE TITLE
Itallian foods website - can customer order? how will owner know when someone has ordered?

### ISSUE THREAD

**Issue by alexislyndon** [m0L3cuL3/ITCC-13-FINAL-PROJECT#9]
Naay database? 
How many  pages ang site? 
Mobile first or desktop?
How many pages?

**Comment by m0L3cuL3** [comment]
1. Naa pero not sure if normalized, probably design ta ug ERD una.
2. 4 pages
3. Desktop

**Comment by alexislyndon** [comment]
unsa ang 4 pages @m0L3cuL3 ?

I can do the ERD

**Comment by m0L3cuL3** [comment]
3 pages: (kani ra i think)
- Home
- Sign Up
- Sign In

**Comment by alexislyndon** [comment]
owner has admin page/panel(inaccessible to customers) 
_pending > received and preparing? > ready_ | _cancelled, cancelled by marzia_
customers - no need for sign up, can track order thru a reference number
customers can change order in a reference number as long as its still pending
